### ISSUE TITLE
Fix icon's in readme file won't work with the GitHub dark mode

### ISSUE THREAD

**Issue by a4h8** [styfle/awesome-online-ide#108]
List title icons does not appear with GitHub dark mode switched on.

**Comment by styfle** [comment]
It works correctly on the website https://styfle.dev/projects/awesome-online-ide

**Comment by VladPutinEu** [comment]
@a4h8 There really is no way to fix other than adding a white background too all of the icons, which isn't a good idea. Use GitHub for contributing and the website for viewing.
