### ISSUE TITLE
Add codepy.io

### ISSUE THREAD

**Issue by TalhaAnis** [styfle/awesome-online-ide#111]
Please add **https://codepy.io**
It is basically an **Online Python, NodeJS, and Golang** compiler/Interpreter.
You can use this tool to **Write, Save, Run and Share** your code with others.
Your code is automatically being synced and saved as you type. Once you finish typing your code, you can run it and share the code link with others to see your code.

**Comment by styfle** [comment]
<img width="893" alt="image" src="https://github.com/user-attachments/assets/f2e6ad8a-a2be-4921-947c-d2228efdfb13">
