### ISSUE TITLE
Add Code Playground

### ISSUE THREAD

**Issue by hemantasapkota** [styfle/awesome-online-ide#112]
Please add https://codeplayground.app

It's an awesome mobile IDE for iPhone and iPad, and it supports 20 languages including Python 3, Javascript, Typescript, Go, and many more.

Full list of features:
1. 20 languages supports
2. Built-in tutorials for all the languages
3. Run snippets
4. Autocomplete for Javascript and Typescript
5. Share snippets
6. Create workspaces

Thanks

**Comment by styfle** [comment]
Does it work in a web browser?

The readme mentions:

> An "Online IDE" has the features mentioned above but runs in a web browser instead of installing as a native application.

**Comment by hemantasapkota** [comment]
@styfle ah! didn't read the docs 😅. It does not work on the browser. I will touch base again in the future. Closing for now.
