### ISSUE TITLE
Add Livecodes

### ISSUE THREAD

**Issue by Brikaa** [styfle/awesome-online-ide#128]
[Livecodes](https://github.com/live-codes/livecodes) by @hatemhosny runs multiple languages (with support for multiple libraries and frameworks) directly in the browser without server round trips. It is open source and self-hostable. It has [multiple other features](https://livecodes.io/docs/features/).

Maybe @hatemhosny might be better suited than me to provide a concise description.

**Comment by hatemhosny** [comment]
Thank you @Brikaa 
I have opened a PR to add LiveCodes: #129
