### ISSUE TITLE
Breakout self-hosting and hosted

### ISSUE THREAD

**Issue by colonelpopcorn** [styfle/awesome-online-ide#18]
This is a pretty awesome repository, however there is a lack of information around pricing and the ability to self host some of these products. For example, Codenvy is pretty much just a SaaS for Eclipse Che which is self-hostable and AWS C9 is also self-hostable with Docker. Not sure if there should be duplicate entries or tags for self-hosting, cloud hosted, free, freemium, etc.

**Comment by styfle** [comment]
Good point!

I think adding an icon to indicate Self-hosted could be useful, like the icon to indicate Open Source.

This is called Online IDE so I expect to be able to use all of them without self-hosting, even if they have a self-host option.

Should we use the docker icon to indicate this? 

<a href="https://cdn.jsdelivr.net/npm/simple-icons@1.2.7/icons/docker.svg">
<img src="https://cdn.jsdelivr.net/npm/simple-icons@1.2.7/icons/docker.svg" width=32 height=32 />
</a>

**Comment by styfle** [comment]
Fixed in #19
