### ISSUE TITLE
Codenvy.io/Eclipse Che missing

### ISSUE THREAD

**Issue by esantoro** [styfle/awesome-online-ide#2]
Hello,
this list should definitely include Eclipse Che and Codenvy.io.

Eclipse che is a full port of the Eclipse ide for the web, with a very powerful and functional backend. Codenvy.io is a commercial offering based on Eclipse Che that has a generous free plan.

References:

- https://codenvy.io
- https://www.eclipse.org/che/

**Comment by styfle** [comment]
Hi @esantoro, thanks for the suggestion!

I'll check it out! 👍

**Comment by styfle** [comment]
I added code envy.
It looks like it's open source too https://github.com/codenvy/codenvy
