### ISSUE TITLE
Feature: add Glitch and repl.it

### ISSUE THREAD

**Issue by dbkaplun** [styfle/awesome-online-ide#24]
Thanks for considering!

**Comment by senthilkumar-kj** [comment]
That someone is the CEO of Gitlab :)

**Comment by styfle** [comment]
@senthilkumar-kj Wow! 😮 

![image](http://gifimage.net/wp-content/uploads/2017/06/jaw-drop-gif-13.gif)

**Comment by styfle** [comment]
I must have confused this ticket with another one...not sure why I mentioned GitLab here 🤔 

Again, Glitch would be welcomed as a PR.
It looks like repl.it is already in the list 👍

**Comment by amasad** [comment]
@styfle we fit in both full IDE and snippets. Are you open to putting us in both?

**Comment by amasad** [comment]
Our appeoach is blurring the line between repl/snippets and IDE. It should
be adaptable and should reveal itself anytime you need the power.

E.g. go to any language, say node.js, and open a port, and it will open a
webview for you to dev against.

Or you can go straight to developing an app, say in ReactReason:

https://repl.it/languages/reactre

More info here: https://repl.it/site/blog/platform

If we have to go with one, I say lets go with an IDE :)

**Comment by styfle** [comment]
@amasad Ok, let's go with IDE!

Would you like to submit a PR? 😄

**Comment by styfle** [comment]
@dbkaplun I'm closing this issue since both Glitch and Repl.it are in the readme now, thanks 👍
