### ISSUE TITLE
Add Code.xyz

### ISSUE THREAD

**Issue by keithwhor** [styfle/awesome-online-ide#26]
Hey there! Great list :).

We launched https://code.xyz a couple of weeks ago ([here's our announcement](https://stdlib.com/blog/stripe-code-xyz/)).

[Code.xyz](https://code.xyz) is a full IDE (multi-project, file support) optimized for building APIs using serverless functions. Please let me know if you have any questions!

Cheers,
- Keith

**Comment by styfle** [comment]
Hi Keith, thanks for the suggestion!

It looks pretty sleek and I like the domain name 👍 

What languages are supported?

**Comment by keithwhor** [comment]
In theory you can shell out to other languages, but I'm not sure I'm aware of any of our developers or customers doing that. It's primarily an IDE for APIs built using Node.js (8.x) - function as a service. i.e. you write functions in the `functions` folder, hit run, they're deployed and API documentation and more is automatically generated for them. :)

**Comment by styfle** [comment]
Ok, feel free to submit a PR to add it 😄

**Comment by VladPutinEu** [comment]
This still hasn't been closed.

**Comment by VladPutinEu** [comment]
@styfle Could you please add it and close this issue?

**Comment by styfle** [comment]
<img width="541" alt="image" src="https://github.com/user-attachments/assets/3f021efc-5aa0-411f-b199-fc82f0bf3d75">
