### ISSUE TITLE
Does coderpad count?

### ISSUE THREAD

**Issue by ubershmekel** [styfle/awesome-online-ide#27]
You can run different kinds of snippets in various languages. Though it doesn't have any concept of multiple files, I think.

https://coderpad.io/demo

**Comment by styfle** [comment]
Hi Yuval, thanks for the suggestion!

This looks like it could be in the Snippets section.

I just tried the PostgreSQL demo and I got an error though

![image](https://user-images.githubusercontent.com/229881/41499909-ed0f8422-7156-11e8-87f7-11906828aa36.png)

**Comment by VladPutinEu** [comment]
@styfle Could you please add it?

**Comment by VladPutinEu** [comment]
@styfle It's been a while, could you please re-evaluate it?

**Comment by styfle** [comment]
I think the pricing is not worth it. Also this seems to be focused on interviews and not general purpose IDE so I don't think it belongs in this list.

![pricing](https://user-images.githubusercontent.com/229881/110258173-3ad3f980-7f6f-11eb-90ff-fb047a0de138.png)

**Comment by VladPutinEu** [comment]
> I think the pricing is not worth it. Also this seems to be focused on interviews and not general purpose IDE so I don't think it belongs in this list.
> 
> ![pricing](https://user-images.githubusercontent.com/229881/110258173-3ad3f980-7f6f-11eb-90ff-fb047a0de138.png)

Agreed.
