### ISSUE TITLE
RunKit does not require a sign-in

### ISSUE THREAD

**Issue by tolmasky** [styfle/awesome-online-ide#30]
Just a note on the RunKit description: you don't have to sign in. The register page has a "skip this" button. Additionally, RunKit embeds don't require a sign in to use nor to create (https://runkit.com/docs/embed -- as seen in for example: https://expressjs.com/en/starter/hello-world.html ).

**Comment by styfle** [comment]
Looks like this was already changed so I'll close this issue

**Comment by styfle** [comment]
Oh I see there was no icon but it was in the description.

I'll fix in #94
