### ISSUE TITLE
Add Webpaw.net

### ISSUE THREAD

**Issue by alidotnet** [styfle/awesome-online-ide#70]
- Webpaw.net is a web-based code testing/authoring environment with realtime collaboration support.
- It provides a console for debugging, and currently supports HTML, JavaScript/TypeScript/CoffeeScript, CSS/SCSS languages.
- Import is currently possible from GitHub, JSfiddle/Codepen. Even HTML files created separately can be imported.
- Provides several development utilities such as file upload, google font selection helper, icon selection helper, color palette, WebService tester, sample images (with search option) and a JSON format parser.
- Supports multiple view layouts, highly customizable UI, and two themes (light/dark) as well.
- Editor supports automatic HTML tag closing, some auto-complete features.
- Auto-run and auto-save features.
- Social login support (currently with Google and GitHub)
- Provides features for saving separate HTML, CSS or JS file or even the whole package as a ZIP file or a "all-in-one" HTML file.

**Comment by Lucia9176** [comment]
[Webpaw.net](play golden ) 
![repository-open-graph-template](https://user-images.githubusercontent.com/66771682/84365163-5a511800-abd1-11ea-86e9-04eff6e350ea.png)

> @hungsu #86 

- [ ] 

1. Gratulujem ahoj 

- [Bratislava ](play golden.com) @breandan @SjonHortensius @hermanzdosilovic @wylieconlon 

>  webpaw.net. Html
![IMG_2020-05-07-10380717](https://user-images.githubusercontent.com/66771682/84365666-14e11a80-abd2-11ea-99e6-a54744565afd.jpg)
 JSON[Webpaw.net](play golden.jSON)

**Comment by Lucia9176** [comment]
Play
