### ISSUE TITLE
Add Liveweave

### ISSUE THREAD

**Issue by p3k** [styfle/awesome-online-ide#79]
Similar to Codepen and still allowing anonymous save.

https://liveweave.com

**Comment by styfle** [comment]
There are a ton of these under web snippets.

What does Liveweave do that the others don't? Is it even open source?

https://github.com/styfle/awesome-online-ide#web-snippets

**Comment by VladPutinEu** [comment]
@styfle Livewave is not open source, but it has a Web Editor, CSS Explorer, Color Explorer, and a Vector Graphics Editor, all in one website! It also lets you use external CSS & JavaScript libraries without having to search for them online. It's also very easy to use.
