### ISSUE TITLE
Add webide.se

### ISSUE THREAD

**Issue by Z3TA** [styfle/awesome-online-ide#83]
IDE +shell for JS 
Http://webide.se/

Can also run locally:
npm i -g webide.se

**Comment by VladPutinEu** [comment]
@styfle Please add it.

**Comment by styfle** [comment]
I started modifying the default HTML doc and there was no intellisense/autocomplete.

The I switched to a different browser tab and switched back which caused an error.

![image](https://user-images.githubusercontent.com/229881/95099669-307eac80-06fe-11eb-90d9-7bc36f15587a.png)

**Comment by VladPutinEu** [comment]
I agree, it's pretty buggy. Has some nice features though.

**Comment by Z3TA** [comment]
There _are_ som basic HTML support:
* Auto-indentation of _some_ HTML elements. 
* Autocomplete of most standard HTML elements (using tab-key)
* Color highlight for <tags> even when in JavaScript/PHP/ASP strings and JSX
* Intelligent tag/element close (using tab-key) eg. you can click tab anywhere and it will add a </tag> for the matching tag/element.

I'm currently working on adding more standard HTML elements. (did not have html. head and body as they are not used so often, but adding them now).

Also begun working on CSS intellicense.

The editor already have basic support for JavaScript, like scope aware auto-complete (the code is parsed on every key stroke using an incremental parser built in vanilla JS) and type inference, eg. it parses functions to figure out what a function returns so it can auto-complete prototype and parameter/methods from variables returned from functions.

Please list the HTML intellicense functions you wish it had @styfle and I will gladly add them. 

Yes there is a lot of bugs @VladPutinEu I've intentionally built the app with "defensive coding"  so that every slightly smell of error will surface. This error in particular is due to a timeout error. The editor has to spin up a new virtual machine/server (VM/VPS) just so the user can run docker, because Docker needs root (because I don't want to give all users root access to the dedicated root/host server(s).

**Comment by VladPutinEu** [comment]
@Z3TA, I really like the idea and all the work you've done so far, but I believe that we need to give it some time to be more stable. This seems to be a work in progress, and not quite ready yet to be on this list. Please make an additional issue when you feel like your IDE is ready.

**Comment by Z3TA** [comment]
I think It's ready to be added, with an "alpha"/beta warning if you think it's not up to pair. What I need now is feedback from users.
I've added automated error reports, so whenever a user steps on a bug I will get a message.

Most online IDE's now a day is based on VS-code which has 20 or so engineers working full time and this is currently a one-man- on-weekends project, so it's difficult to keep up with the quality. My plan is to listen to users and try to find a niche so that I can start deleting features rather then adding new unpolished ones.

**Comment by VladPutinEu** [comment]
@styfle Webside has improved a lot since the test, I think it might be a good idea to look at it again.

**Comment by styfle** [comment]
I still can't figure out how to use this thing. Its just a bunch of modals.

![image](https://user-images.githubusercontent.com/229881/110258277-c8174e00-7f6f-11eb-8b9a-269b58e07dc2.png)

![image](https://user-images.githubusercontent.com/229881/110258281-cf3e5c00-7f6f-11eb-865f-16f9befaac26.png)

![image](https://user-images.githubusercontent.com/229881/110258289-e1b89580-7f6f-11eb-8603-811bca3a8d3b.png)

![image](https://user-images.githubusercontent.com/229881/110258304-f301a200-7f6f-11eb-840e-9a25882a0ca3.png)

**Comment by VladPutinEu** [comment]
> I still can't figure out how to use this thing. Its just a bunch of modals.
> 
> ![image](https://user-images.githubusercontent.com/229881/110258277-c8174e00-7f6f-11eb-8b9a-269b58e07dc2.png)
> 
> ![image](https://user-images.githubusercontent.com/229881/110258281-cf3e5c00-7f6f-11eb-865f-16f9befaac26.png)
> 
> ![image](https://user-images.githubusercontent.com/229881/110258289-e1b89580-7f6f-11eb-8603-811bca3a8d3b.png)
> 
> ![image](https://user-images.githubusercontent.com/229881/110258304-f301a200-7f6f-11eb-840e-9a25882a0ca3.png)

I agree, it is very buggy.
